#on:
#  # Trigger the workflow on push or pull request,
#  # but only for the develop branch
#  push:
#    branches:
#      - develop
#      - 'releases/**'
#      - 'feature/**'
#  pull_request:
#    branches:
#      - develop
#
#name: npm build, lint, test and publish
#jobs:
#  build-and-publish:
#    name: build and publish
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node: [ '10', '8' ]
#    steps:
#      - uses: actions/checkout@master
#      - name: npm install
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node }}
#      - run: npm install
#      - run: npm run build
#      - run: npm run test
#      - run: apt-get install awscli
#
#      - name: serverless deploy
#        run: npx serverless deploy
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#

name: Master CI/CD

on:
  # Trigger the workflow on push or pull request,
  # but only for the develop branch
  push:
    branches:
      - develop
      - 'releases/**'
      - 'feature/**'
  pull_request:
    branches:
      - develop

jobs:
  primary:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - uses: actions/checkout@v1
                - name: Decrypt large secret
                run: ./.github/scripts/decrypt_secret.sh
                env:
                  LARGE_SECRET_PASSPHRASE: $
        # This command is just an example to show your secret being printed
        # Ensure you remove any print statements of your secrets. GitHub does
        # not hide secrets that use this workaround.
                - name: Test printing your secret (Remove this step in production)
                  run: cat $HOME/secrets/my_secret.json
      - name: serverless deploy
        if: contains( github.ref, 'develop' )
        run: npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}