on:
  # Trigger the workflow on push or pull request,
  # but only for the develop branch
  push:
    branches:
      - develop
      - 'releases/**'
      - 'feature/**'
  pull_request:
    branches:
      - develop

name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '8' ]
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: apt-get install awscli

      - name: serverless deploy
        run: npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
]
