on:
  # Trigger the workflow on push or pull request,
  # but only for the develop branch
  push:
    branches:
      - develop
      - 'releases/**'
      - 'feature/**'
  pull_request:
    branches:
      - develop

name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '8' ]
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install

      - name: npm test
        uses: actions/npm@master
        with:
          args: run test
      - name: npm lint
        uses: actions/npm@master
        with:
          args: run lint
      - name: deploy aws staging
        if: contains( github.ref, 'develop/' )
        uses: actions/aws/cli@master
        with:
          args: s3 cp build s3://www.example.com --recursive --exclude ".git/*" --exlucde ".github/*"
          secrets:
            AWS_ACCESS_KEY_ID : adasdas
            AWS_SECRET_ACCESS_KEY: sadsdafdsa
          uses: actions/aws/cli@master
